run etcd as a container in the hub pod

diff --git a/jupyterhub/templates/hub/deployment.yaml b/jupyterhub/templates/hub/deployment.yaml
--- a/jupyterhub/templates/hub/deployment.yaml
+++ b/jupyterhub/templates/hub/deployment.yaml
@@ -17,7 +17,7 @@ spec:
         {{- /* Changes here will cause the Deployment to restart the pods. */}}
         {{- include "jupyterhub.matchLabels" . | nindent 8 }}
         hub.jupyter.org/network-access-proxy-api: "true"
-        hub.jupyter.org/network-access-proxy-etcd: "true"
+        hub.jupyter.org/network-access-etcd: "true"
         hub.jupyter.org/network-access-proxy-http: "true"
         hub.jupyter.org/network-access-singleuser: "true"
         {{- if .Values.hub.labels }}
@@ -46,10 +46,12 @@ spec:
         {{- if .Values.hub.extraVolumes }}
         {{- .Values.hub.extraVolumes | toYaml | trimSuffix "\n" | nindent 8 }}
         {{- end }}
-        {{- if eq .Values.hub.db.type "sqlite-pvc" }}
         - name: hub-db-dir
+        {{- if eq .Values.hub.db.type "sqlite-pvc" }}
           persistentVolumeClaim:
             claimName: hub-db-dir
+        {{- else }}
+          emptyDir: {}
         {{- end }}
       {{- if .Values.rbac.enabled }}
       serviceAccountName: hub
@@ -65,6 +67,76 @@ spec:
         {{- if .Values.hub.extraContainers }}
         {{- .Values.hub.extraContainers | toYaml | trimSuffix "\n" | nindent 8 }}
         {{- end }}
+        - name: etcd
+          env:
+            - name: ETCDCTL_API
+              value: '3'
+            # etcd warns about unrecognized ETCD_* variables
+            # so we can't use obvious ETCD_USERNAME, etc
+            - name: PASSWORD_ETCD
+              valueFrom:
+                secretKeyRef:
+                  name: hub-secret
+                  key: etcd.password
+            - name: USERNAME_ETCD
+              valueFrom:
+                secretKeyRef:
+                  name: hub-secret
+                  key: etcd.username
+          image: {{ .Values.proxy.etcd.image.name }}:{{ .Values.proxy.etcd.image.tag }}
+          imagePullPolicy: {{ .Values.proxy.etcd.imagePullPolicy }}
+          command:
+            - etcd
+            - --data-dir=/srv/jupyterhub/etcd/default.etcd
+            - --listen-client-urls=http://0.0.0.0:2379
+            - --advertise-client-urls=http://127.0.0.1:2379
+          lifecycle:
+            # postStart hook to enable etcd username+password
+            postStart:
+              exec:
+                command:
+                  - sh
+                  - -c
+                  - |
+                    set -e
+                    # step 1. check if auth works *or* is not yet enabled
+                    # if the password changes, this will fail and should force resetting
+                    # all of etcd state
+                    etcdctl --user ${USERNAME_ETCD}:${PASSWORD_ETCD} user list || (
+                      echo "etcd auth invalid, resetting etcd"
+                      rm -rf /srv/jupyterhub/etcd/default.etcd
+                      exit 1
+                    )
+                    # step 2. ensure users exists
+                    if [[ -z "$(etcdctl --user ${USERNAME_ETCD}:${PASSWORD_ETCD} user list)" ]]; then
+                      # no users listed, setup auth
+                      # first setup root user, which is required for auth
+                      etcdctl user add root:${PASSWORD_ETCD}
+                      etcdctl auth enable
+                      # next, create the user that will actually be used
+                      # and grant the user root access
+                      if [[ ${USERNAME_ETCD} != "root" ]]; then
+                        etcdctl --user root:${PASSWORD_ETCD} user add ${USERNAME_ETCD}:${PASSWORD_ETCD}
+                        etcdctl --user root:${PASSWORD_ETCD} user grant-role ${USERNAME_ETCD} root
+                      fi
+                      # step 3. verify authentication
+                      echo "check auth"
+                      etcdctl --user ${USERNAME_ETCD}:${PASSWORD_ETCD} user list
+                    fi
+          ports:
+            - containerPort: 2379
+              name: etcd
+          resources:
+            {{- .Values.proxy.etcd.resources | toYaml | trimSuffix "\n" | nindent 12 }}
+          securityContext:
+            runAsUser: {{ .Values.hub.uid }}
+            fsGroup: {{ .Values.hub.fsGid }}
+          volumeMounts:
+            - mountPath: /srv/jupyterhub
+              name: hub-db-dir
+              {{- if .Values.hub.db.pvc.subPath }}
+              subPath: {{ .Values.hub.db.pvc.subPath | quote }}
+              {{- end }}
         - name: hub
           image: {{ .Values.hub.image.name }}:{{ .Values.hub.image.tag }}
           command:
@@ -102,13 +174,11 @@ spec:
             {{- if .Values.hub.extraVolumeMounts }}
             {{- .Values.hub.extraVolumeMounts | toYaml | trimSuffix "\n" | nindent 12 }}
             {{- end }}
-            {{- if eq .Values.hub.db.type "sqlite-pvc" }}
             - mountPath: /srv/jupyterhub
               name: hub-db-dir
               {{- if .Values.hub.db.pvc.subPath }}
               subPath: {{ .Values.hub.db.pvc.subPath | quote }}
               {{- end }}
-            {{- end }}
           resources:
             {{- .Values.hub.resources | toYaml | trimSuffix "\n" | nindent 12 }}
           imagePullPolicy: {{ .Values.hub.imagePullPolicy }}
@@ -171,3 +241,4 @@ spec:
           ports:
             - containerPort: 8081
               name: hub
+
